### ISSUE TITLE
FFF Client missing in release 1.1 

### ISSUE THREAD

**Issue by Ep1cSpartan** [Macronair/TheMillionaireGame#51] opened 2023-11-21 07:22 UTC
First of all: Thanks a lot for the latest release. I am looking for the FastestFingerClient in the release but I am unable to find it. There are only three .exe files in it, 2x MillionaireGame.exe and QEDIT.exe.

**Comment by Macronair** [comment] 2023-11-21 11:13
Oops! Sorry for that. Didn't noticed that when making the zip file. I will replace it with the correct files. 😉

**Comment by Ep1cSpartan** [comment] 2023-11-21 11:50
No worries, just happy to help :) Thanks for looking into it

**Comment by Macronair** [comment] 2023-11-21 12:31
I re-uploaded the zip file with the correct files. And the duplicate of the main application is removed from it. ;)

**Closed by Macronair** 2023-11-21 12:31 UTC
